FROM golang:1.18-alpine

# I think it does not work
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN mkdir /app

COPY . /app

WORKDIR /app

CMD [ "air", "./cmd/gbm" ]